import type { FC } from 'react'
import {
  BtrCh01HumanGlue,
  BtrCh01WhenDoThat,
  BtrCh01EffortOrRun,
  BtrCh02FourParts,
  BtrCh02Webhook,
  BtrCh02ThreeBenches,
  BtrCh02WhatYouOwn,
  BtrCh03Canyon,
  BtrCh03OneJob,
  BtrCh03FailurePath,
} from './btrCh01-03'
import {
  BtrCh04WeekAudit,
  BtrCh04RuleOfThree,
  BtrCh04NeverAutomate,
  BtrCh04QuickWins,
  BtrCh05ReadEntry,
  BtrCh05LibraryMap,
  BtrCh05SignaturePreview,
  BtrCh05ReturnsCluster,
  BtrCh06HumanLoop,
  BtrCh06TwoMinuteCheck,
  BtrCh07Decay,
  BtrCh07Ceiling,
  BtrCh07LawTravels,
  BtrCh08AiBelongs,
  BtrCh08HypeTax,
  BtrCh08PatienceGates,
  BtrCh08MatchModel,
} from './btrCh04-08'
import {
  BtrCh09NervousSystem,
  BtrCh09SignatureFlow,
  BtrCh09SentReceived,
  BtrCh09Watcher,
  BtrCh09Layers,
  BtrCh10SplitWorkflow,
  BtrCh10Crossover,
  BtrCh10SocialFailures,
  BtrCh11DescribingBuilds,
  BtrCh11FourChecks,
} from './btrCh09-11'

type DiagramProps = { caption: string }

/** All Built to Run diagram IDs → components. */
export const BTR_DIAGRAMS: Record<string, FC<DiagramProps>> = {
  'btr-ch01-human-glue': BtrCh01HumanGlue,
  'btr-ch01-when-do-that': BtrCh01WhenDoThat,
  'btr-ch01-effort-or-run': BtrCh01EffortOrRun,
  'btr-ch02-four-parts': BtrCh02FourParts,
  'btr-ch02-webhook': BtrCh02Webhook,
  'btr-ch02-three-benches': BtrCh02ThreeBenches,
  'btr-ch02-what-you-own': BtrCh02WhatYouOwn,
  'btr-ch03-canyon': BtrCh03Canyon,
  'btr-ch03-one-job': BtrCh03OneJob,
  'btr-ch03-failure-path': BtrCh03FailurePath,
  'btr-ch04-week-audit': BtrCh04WeekAudit,
  'btr-ch04-rule-of-three': BtrCh04RuleOfThree,
  'btr-ch04-never-automate': BtrCh04NeverAutomate,
  'btr-ch04-quick-wins': BtrCh04QuickWins,
  'btr-ch05-read-entry': BtrCh05ReadEntry,
  'btr-ch05-library-map': BtrCh05LibraryMap,
  'btr-ch05-signature-preview': BtrCh05SignaturePreview,
  'btr-ch05-returns-cluster': BtrCh05ReturnsCluster,
  'btr-ch06-human-loop': BtrCh06HumanLoop,
  'btr-ch06-two-minute-check': BtrCh06TwoMinuteCheck,
  'btr-ch07-decay': BtrCh07Decay,
  'btr-ch07-ceiling': BtrCh07Ceiling,
  'btr-ch07-law-travels': BtrCh07LawTravels,
  'btr-ch08-ai-belongs': BtrCh08AiBelongs,
  'btr-ch08-hype-tax': BtrCh08HypeTax,
  'btr-ch08-patience-gates': BtrCh08PatienceGates,
  'btr-ch08-match-model': BtrCh08MatchModel,
  'btr-ch09-nervous-system': BtrCh09NervousSystem,
  'btr-ch09-signature-flow': BtrCh09SignatureFlow,
  'btr-ch09-sent-received': BtrCh09SentReceived,
  'btr-ch09-watcher': BtrCh09Watcher,
  'btr-ch09-layers': BtrCh09Layers,
  'btr-ch10-split-workflow': BtrCh10SplitWorkflow,
  'btr-ch10-crossover': BtrCh10Crossover,
  'btr-ch10-social-failures': BtrCh10SocialFailures,
  'btr-ch11-describing-builds': BtrCh11DescribingBuilds,
  'btr-ch11-four-checks': BtrCh11FourChecks,
}

export const BTR_DIAGRAM_IDS = Object.keys(BTR_DIAGRAMS)
