
import { ServiceDetail } from '../types';

export const SERVICES: ServiceDetail[] = [
  {
    id: 'pillar1',
    title: 'WEBSITES & E-COMMERCE',
    subtitle: 'The Front Door',
    systemGroup: 'GET CLIENTS',
    symptom: 'Are you losing leads in spreadsheets?',
    description: 'We build clean, fast websites that catch leads, qualify enquiries, and feed your pipeline while you focus on running the business. No bloated page builders, no slow templates. Modern code that loads in under a second with proper SEO, forms, and tracking built in from day one.',
    smallCardBody: 'We build your website so it catches leads and feeds them straight into your system',
    features: ['Smart Lead Forms', 'Inventory Synced to Sales', 'Fast, Mobile-First Design'],
    visualPrompt: 'geometric',
  },
  {
    id: 'pillar2',
    title: 'CRM & LEAD TRACKING',
    subtitle: 'The Memory',
    systemGroup: 'GET CLIENTS',
    symptom: 'Do you know exactly where every deal is stuck?',
    description: 'We set up a CRM that captures every enquiry, follows up automatically, and shows you exactly where every deal stands. You see your entire pipeline at a glance, you know which marketing channels are working, and you never forget to follow up on a quote again.',
    smallCardBody: 'Every lead, every deal, and every follow-up tracked in one place',
    features: ['Visual Deal Pipeline', 'Clean Data', 'Auto Follow-Up Reminders'],
    visualPrompt: 'network',
  },
  {
    id: 'pillar3',
    title: 'AUTOMATION',
    subtitle: 'The Engine',
    systemGroup: 'GET CLIENTS',
    symptom: 'Are you manually typing invoices and contracts?',
    description: 'You tell us what you want to happen and we build the system that runs it. Form submitted, reply sent. Deal closed, invoice generated. We connect your tools, set the rules, and make it run every time without you in the middle.',
    smallCardBody: 'Data moves between your tools without anyone doing it manually',
    features: ['Instant Data Sync', 'Smart Email Sequences', 'Auto-Generated Invoices'],
    visualPrompt: 'flow',
  },
  {
    id: 'pillar4',
    title: 'AI ASSISTANTS',
    subtitle: 'The Assistant',
    systemGroup: 'SCALE FASTER',
    symptom: 'Is your team answering the same 5 questions all day?',
    description: 'We build AI assistants that know your business inside out. They answer your phone, reply to enquiries, and handle the repetitive questions so you and your team don\'t have to. We feed it your documents, your pricing, your processes, and your rules so it responds using your actual information.',
    smallCardBody: 'AI that answers your phone, qualifies leads, and handles repetitive questions',
    features: ['AI Phone Answering', 'Internal Knowledge Bots', 'Built-In Safety Rules'],
    visualPrompt: 'neural',
  },
  {
    id: 'pillar5',
    title: 'CONTENT SYSTEMS',
    subtitle: 'The Amplifier',
    systemGroup: 'SCALE FASTER',
    symptom: 'Is content creation taking hours instead of minutes?',
    description: 'We build systems that turn one hour of your time into a month of content. You record a voice memo or jump on a quick call and the system turns that into blog posts that rank on Google, social posts that keep you visible, and emails that bring people back. You talk and we handle the rest.',
    smallCardBody: 'One conversation turned into a month of content across every platform',
    features: ['AI Voice & Video Cloning', 'Auto-Post to All Platforms', 'YouTube & Podcast Setup'],
    visualPrompt: 'sequential',
  },
  {
    id: 'pillar6',
    title: 'TEAM TRAINING',
    subtitle: 'The Coach',
    systemGroup: 'SCALE FASTER',
    symptom: 'Did you buy software that nobody uses?',
    description: 'You can buy the best software in the world but if your team won\'t use it you\'ve wasted your money. We build bite-sized training videos, clear process guides, and internal AI mentors that answer questions on the spot. We help you communicate the reason behind the change so your team stops resisting and starts adopting.',
    smallCardBody: 'Short videos, clear guides, and support until your team actually uses the tools',
    features: ['Bite-Sized Training Videos', 'Step-by-Step Guides', 'Team Q&A Library'],
    visualPrompt: 'waves',
  },
  {
    id: 'pillar7',
    title: 'DASHBOARDS & REPORTING',
    subtitle: 'The Dashboard',
    systemGroup: 'SEE CLEARLY',
    symptom: 'Are you steering the business by gut feeling?',
    description: 'You shouldn\'t have to wait for the accountant to tell you if last month was good or bad. We pull data from your CRM, your accounting software, and your marketing platforms into one dashboard. You see which channels bring in paying clients, which services are profitable, and what the next 90 days look like.',
    smallCardBody: 'Revenue, margin, and pipeline on one screen, updated live',
    features: ['Live Revenue Tracking', 'Forecasting & Projections', 'One-Screen Business Health'],
    visualPrompt: 'dashboard',
  }
];
