import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'toolkitItem',
  title: 'Toolkit Item',
  type: 'document',
  groups: [
    {name: 'core', title: 'Core setup', default: true},
    {name: 'content', title: 'Page content'},
    {name: 'seo', title: 'SEO & routing'},
    {name: 'publishing', title: 'Publishing & author'},
  ],
  fields: [
    defineField({
      name: 'name',
      title: 'Tool name',
      type: 'string',
      group: 'core',
      description: 'The tool as people search for it, e.g. ChatGPT, Claude, Perplexity.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'core',
      description: 'Sets the page URL, e.g. /toolkit/chatgpt.',
      options: {source: 'name', maxLength: 96},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'mainImage',
      title: 'Main visual',
      type: 'image',
      group: 'core',
      description: 'Hero image on the tool page (16:9 works best). Same role as a blog post main visual.',
      options: {hotspot: true},
      fields: [
        defineField({
          name: 'alt',
          title: 'Alt text',
          type: 'string',
          description: 'Describe the image for accessibility and SEO, e.g. "ChatGPT logo".',
        }),
      ],
    }),
    defineField({
      name: 'tagline',
      title: 'Tagline',
      type: 'string',
      group: 'core',
      description: 'One line on what it gives the owner, outcome first. No full stop. Max 160 characters (about one short post line).',
      validation: (Rule) => Rule.max(160),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      group: 'core',
      description: 'The primary filter. What the tool is for.',
      options: {
        list: [
          {title: 'Chat & research', value: 'chat-research'},
          {title: 'Writing & content', value: 'writing-content'},
          {title: 'Images & design', value: 'images-design'},
          {title: 'Video', value: 'video'},
          {title: 'Voice & audio', value: 'voice-audio'},
          {title: 'Meetings & notes', value: 'meetings-notes'},
          {title: 'Coding', value: 'coding'},
          {title: 'Automation & agents', value: 'automation-agents'},
        ],
        layout: 'dropdown',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'phase',
      title: 'Phase (optional)',
      type: 'string',
      group: 'core',
      description: 'Not used as a launch filter. Reserved for the wider directory later.',
      options: {
        list: [
          {title: 'Get Clients', value: 'get-clients'},
          {title: 'Scale Faster', value: 'scale-faster'},
          {title: 'See Clearly', value: 'see-clearly'},
        ],
        layout: 'radio',
      },
    }),
    defineField({
      name: 'pricingModel',
      title: 'Pricing model',
      type: 'string',
      group: 'core',
      description: 'Useful metadata and an optional secondary filter.',
      options: {
        list: [
          {title: 'Free', value: 'free'},
          {title: 'Freemium', value: 'freemium'},
          {title: 'Free trial', value: 'free-trial'},
          {title: 'Paid', value: 'paid'},
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'picks',
      title: 'Editorial badges',
      type: 'array',
      group: 'core',
      of: [{type: 'string'}],
      description: 'Your picks. Choose any. Used to drive clicks toward tools we rate.',
      options: {
        list: [
          {title: 'Our pick', value: 'our-pick'},
          {title: 'Best value', value: 'best-value'},
          {title: 'Best for small business', value: 'best-for-small-business'},
        ],
      },
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      group: 'core',
      of: [{type: 'string'}],
      description:
        'Keywords for related blog posts, e.g. ChatGPT, AI assistants. Used to surface related insights on the tool page.',
      options: {layout: 'tags'},
    }),
    defineField({
      name: 'linkType',
      title: 'Link type',
      type: 'string',
      group: 'core',
      description:
        'Drives the disclosure on the page. Affiliate and Referral show a "we may earn a commission" note. Reader discount shows a "you get a discount" note. Standard link shows nothing.',
      initialValue: 'standard',
      options: {
        list: [
          {title: 'Affiliate', value: 'affiliate'},
          {title: 'Referral', value: 'referral'},
          {title: 'Reader discount', value: 'discount'},
          {title: 'Standard link', value: 'standard'},
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'url',
      title: 'Sign-up link',
      type: 'url',
      group: 'core',
      description: 'The affiliate, referral, or plain sign-up URL.',
      validation: (Rule) => Rule.required().uri({scheme: ['https'], allowRelative: false}),
    }),
    defineField({
      name: 'promoCode',
      title: 'Promo or referral code (optional)',
      type: 'string',
      group: 'core',
      description:
        'For tools that give a code rather than a tracked link. Shown on the page if present.',
    }),
    defineField({
      name: 'summary',
      title: 'What it is',
      type: 'text',
      group: 'content',
      rows: 4,
      description: 'Short intro at the top of the page. The deep dive below should not repeat this section.',
      validation: (Rule) => Rule.required().max(400),
    }),
    defineField({
      name: 'benefits',
      title: 'How it helps your business',
      type: 'array',
      group: 'content',
      of: [{type: 'string'}],
      description:
        'Quick scan bullets under “How it helps your business”. Always shown on the detail page.',
    }),
    defineField({
      name: 'body',
      title: 'Deep dive',
      type: 'blockContent',
      group: 'content',
      description:
        'Long-form sections below the intro (what it does, connections, when to pay, etc.). Do not repeat “What it is” here — that lives in Summary.',
    }),
    defineField({
      name: 'focusKeyword',
      title: 'Focus SEO keyword',
      type: 'string',
      group: 'seo',
      description: 'What is the user Googling to find this? (e.g. "ChatGPT for small business").',
    }),
    defineField({
      name: 'metaTitle',
      title: 'SEO title override (optional)',
      type: 'string',
      group: 'seo',
      description:
        'If the tool name is too generic for Google, write a punchy, keyword-rich title here. Max 60 characters.',
      validation: (Rule) => Rule.max(60).warning('Keep under 60 characters for Google.'),
    }),
    defineField({
      name: 'metaDescription',
      title: 'SEO meta description',
      type: 'text',
      group: 'seo',
      rows: 2,
      description: 'The 160-character snippet on Google under the title. Falls back to summary if blank.',
      validation: (Rule) => Rule.max(160),
    }),
    defineField({
      name: 'internalLinkDestination',
      title: 'Internal link routing',
      type: 'string',
      group: 'seo',
      description:
        'Pillar page linked from the “See how we fix this” block above the author. Same options as blog posts.',
      options: {
        list: [
          {title: 'Websites & E-commerce', value: '/pillar1'},
          {title: 'CRM & Lead Tracking', value: '/pillar2'},
          {title: 'Automation', value: '/pillar3'},
          {title: 'AI Assistants', value: '/pillar4'},
          {title: 'Content Systems', value: '/pillar5'},
          {title: 'Team Training', value: '/pillar6'},
          {title: 'Dashboards & Reporting', value: '/pillar7'},
          {title: 'The System (Overview)', value: '/system'},
          {title: 'Homepage', value: '/'},
          {title: 'Contact', value: '/contact'},
        ],
        layout: 'dropdown',
      },
    }),
    defineField({
      name: 'ogImage',
      title: 'Social share image (Open Graph)',
      type: 'image',
      group: 'seo',
      description:
        'Optional 1200×630 image for LinkedIn, Slack, iMessage, etc. Falls back to main visual if blank.',
      options: {hotspot: true},
    }),
    defineField({
      name: 'featured',
      title: 'Featured',
      type: 'boolean',
      group: 'publishing',
      description: 'Surfaces the tool at the top of the index.',
      initialValue: false,
    }),
    defineField({
      name: 'orderRank',
      title: 'Manual order',
      type: 'number',
      group: 'publishing',
      description: 'Lower numbers show first on the toolkit index. Optional.',
    }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'reference',
      group: 'publishing',
      to: [{type: 'author'}],
      description: 'Shown in the meta row and author block at the end of the page.',
    }),
  ],
  orderings: [
    {
      title: 'Featured, then manual order',
      name: 'featuredOrder',
      by: [
        {field: 'featured', direction: 'desc'},
        {field: 'orderRank', direction: 'asc'},
        {field: 'name', direction: 'asc'},
      ],
    },
  ],
  preview: {
    select: {title: 'name', subtitle: 'category', media: 'mainImage'},
  },
})
